# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://docs.astronomer.io/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: airflow_db
      conn_type: postgres
      conn_host: postgres
      conn_schema: postgres
      conn_login: postgres
      conn_password: postgres
      conn_port: 5432
      conn_extra: ""
    - conn_id: aci_db
      conn_type: postgres
      conn_host: <<<YOUR POSTGRES HOST HERE>>>
      conn_schema: <<<YOUR POSTGRES SCHEMA HERE>>>
      conn_login: <<<YOUR POSTGRES LOGIN HERE>>>
      conn_password: <<<YOUR POSTGRES PASSWORD HERE>>>
      conn_port: 5432
      conn_extra: ""
    - conn_id: aci
      conn_type: azure
      conn_login: <<<YOUR AZURE ACI SP CLIENT_ID HERE>>>
      conn_password: <<<YOUR AZURE ACI SP SECRET HERE>>>
      conn_extra: '{"tenantId":"<<<YOUR AZURE TENANT_ID HERE>>>", "subscriptionId":"<<<YOUR AZURE SUBSCRIPTION_ID HERE>>>"}'
    - conn_id: acr
      conn_type: azure_container_registry
      conn_host: <<<YOUR ACR HOST HERE>>>
      conn_login: <<<YOUR ACR LOGIN HERE>>>
      conn_password: <<<YOUR ACR PASSWORD HERE>>>

  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
